version: 0.2

phases:
  install:
    commands:
      
      - echo install serverless framework 
      - npm_config_user=root npm install -g serverless
      
  pre_build:
    commands:
      - echo install pre build commands
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY_ID --profile default
      
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - sls package 
      - sls deploy
  
  post_build:
    commands:
      - echo post build completed on `date`
