version: 0.2


phases:
  install:
    commands:
      
      - echo install serverless framework 
      - npm_config_user=root npm install -g serverless
      
  pre_build:
    commands:
      - echo install pre build commands
      - serverless config credentials --provider aws --key AKIAWSAAQH7YK2V7IJXW --secret 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 --profile testingserverless
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - sls package 
      - sls deploy  --profile testingserverless
  
  post_build:
    commands:
      - echo post build completed on `date`
